import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { resolveWorkspaceDir } from "./runner";

function toTemplateLiteral(value) {
  const text = typeof value === "string" ? value : "";
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function normalizeRoute(route, fallback = "/") {
  if (typeof route !== "string") {
    return fallback;
  }
  const trimmed = route.trim();
  if (!trimmed) {
    return fallback;
  }
  if (!trimmed.startsWith("/")) {
    return `/${trimmed}`;
  }
  return trimmed;
}

function routeToPageFile(workspaceDir, route) {
  const normalized = normalizeRoute(route);
  if (normalized === "/") {
    return path.join(workspaceDir, "app", "page.tsx");
  }
  const parts = normalized
    .replace(/^\//, "")
    .split("/")
    .filter(Boolean)
    .map((segment) => segment.replace(/[^a-zA-Z0-9_-]/g, "-"));
  return path.join(workspaceDir, "app", ...parts, "page.tsx");
}

async function ensureBaseFiles(workspaceDir) {
  await mkdir(path.join(workspaceDir, "app"), { recursive: true });
  await mkdir(path.join(workspaceDir, ".agentic"), { recursive: true });

  await writeFile(
    path.join(workspaceDir, "package.json"),
    JSON.stringify(
      {
        name: "generated-app",
        private: true,
        version: "0.0.1",
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
        },
        dependencies: {
          next: "^16.1.6",
          react: "18.2.0",
          "react-dom": "18.2.0",
        },
      },
      null,
      2
    ),
    "utf8"
  );

  await writeFile(
    path.join(workspaceDir, "next.config.js"),
    "/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nmodule.exports = nextConfig;\n",
    "utf8"
  );

  await writeFile(
    path.join(workspaceDir, "tsconfig.json"),
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: false,
          forceConsistentCasingInFileNames: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"],
        exclude: ["node_modules"],
      },
      null,
      2
    ),
    "utf8"
  );

  await writeFile(
    path.join(workspaceDir, "next-env.d.ts"),
    '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n',
    "utf8"
  );

  await writeFile(
    path.join(workspaceDir, "app", "layout.tsx"),
    `import "./globals.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    "utf8"
  );

  await writeFile(
    path.join(workspaceDir, "app", "globals.css"),
    `*{box-sizing:border-box}body{margin:0;font-family:ui-sans-serif,system-ui,Segoe UI,Roboto,sans-serif;background:#f7f7f8;color:#0f172a}main{padding:32px}a{color:inherit}
`,
    "utf8"
  );

  await writeFile(
    path.join(workspaceDir, "app", "page.tsx"),
    `export default function HomePage() {
  return (
    <main>
      <h1>Generated App</h1>
      <p>Routes will be populated by agent tasks.</p>
    </main>
  );
}
`,
    "utf8"
  );

  await writeFile(
    path.join(workspaceDir, "README.md"),
    "# Generated App\n\nThis app was generated by the ArchiTech agentic pipeline.\n",
    "utf8"
  );
}

export async function ensureJobWorkspace(jobId) {
  const workspaceDir = resolveWorkspaceDir(jobId);
  await mkdir(workspaceDir, { recursive: true });
  await ensureBaseFiles(workspaceDir);
  return workspaceDir;
}

export function createFallbackPageTsx({ title, html }) {
  const safeTitle = title || "Generated Page";
  return `export default function GeneratedPage() {
  return (
    <main>
      <h1>${safeTitle}</h1>
      <section dangerouslySetInnerHTML={{ __html: \`${toTemplateLiteral(html || "")}\` }} />
    </main>
  );
}
`;
}

export async function writeRoutePage({ workspaceDir, route, content }) {
  const pageFile = routeToPageFile(workspaceDir, route);
  await mkdir(path.dirname(pageFile), { recursive: true });
  await writeFile(pageFile, content, "utf8");
  return pageFile;
}

export async function writePageSnapshot({ workspaceDir, taskKey, payload }) {
  const filePath = path.join(workspaceDir, ".agentic", `${taskKey}.json`);
  await writeFile(filePath, JSON.stringify(payload, null, 2), "utf8");
  return filePath;
}

export async function readWorkspaceFile(filePath) {
  try {
    return await readFile(filePath, "utf8");
  } catch {
    return "";
  }
}
